"""Added thehe created_at attribute in orders.

Revision ID: 509eb4950820
Revises: 7465b417ce97
Create Date: 2024-10-20 06:50:21.492904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509eb4950820'
down_revision = '7465b417ce97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
